// <auto-generated />

using System;
using EventManager.WebAPI.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace EventManager.WebAPI.Migrations
{
    [DbContext(typeof(JobContext))]
    internal class JobContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("EventManager.WebAPI.Model.EventJob", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Data")
                    .HasColumnType("TEXT");

                b.Property<long>("Duration")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsCompleted")
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("TimeStamp")
                    .HasColumnType("TEXT");

                b.Property<string>("UserName")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Jobs");
            });
#pragma warning restore 612, 618
        }
    }
}